import type { WorkflowStatus, NodeType } from '@/constants/status';

/** Position on the workflow canvas */
export interface NodePosition {
  x: number;
  y: number;
}

/** Workflow node */
export interface WorkflowNode {
  id: string;
  type: NodeType;
  label: string;
  position: NodePosition;
  data: Record<string, unknown>;
  state?: 'idle' | 'selected' | 'executing' | 'success' | 'error';
}

/** Workflow edge */
export interface WorkflowEdge {
  id: string;
  source: string;
  sourceHandle?: string;
  target: string;
  targetHandle?: string;
  label?: string;
  condition?: string;
}

/** Intent mapping */
export interface IntentMapping {
  intent: string;
  description: string;
  examples: string[];
  targetNodeId: string;
}

/** Workflow rule */
export interface WorkflowRule {
  id: string;
  type: 'retry' | 'escalation' | 'timeout' | 'fallback';
  nodeId: string;
  config: Record<string, unknown>;
}

/** Workflow action */
export interface WorkflowAction {
  id: string;
  type: string;
  nodeId: string;
  config: Record<string, unknown>;
}

/** Workflow fallback */
export interface WorkflowFallback {
  nodeId: string;
  message: string;
  action: 'transfer' | 'voicemail' | 'end' | 'retry';
}

/** Complete workflow contract (generated by frontend, executed by backend) */
export interface WorkflowContract {
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  intents: IntentMapping[];
  rules: WorkflowRule[];
  actions: WorkflowAction[];
  fallbacks: WorkflowFallback[];
}

/** Workflow entity */
export interface Workflow {
  id: string;
  name: string;
  description: string;
  status: WorkflowStatus;
  tenantId: string;
  contract: WorkflowContract;
  version: number;
  agentCount: number;
  lastPublishedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Workflow list item (lightweight) */
export interface WorkflowListItem {
  id: string;
  name: string;
  status: WorkflowStatus;
  agentCount: number;
  nodeCount: number;
  version: number;
  updatedAt: string;
}

/** Workflow validation error */
export interface WorkflowValidationError {
  nodeId?: string;
  edgeId?: string;
  severity: 'error' | 'warning';
  message: string;
  code: string;
}
